# Install python version
FROM python:3.11-slim

# Set the workdir
WORKDIR /app

# Copy all required packages
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend into the container
COPY backend/ .

# Create clean images
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
