# Install node version
FROM node:20

# Set the workdir
WORKDIR /app

# Install all necessary node modules
COPY frontend/package*.json ./
COPY frontend/ .
RUN npm install

# Run react server
CMD ["npm", "start"]
